AlessandroZ/LaZagne

Linux/src/config/manageModules.py, Linux/src/softwares/wallet/gnome.py, Linux/src/softwares/wallet/kde.py, README.md
New module (*kde*) implemented to steal credentials stored in KWallet (Linux).
The following command should be used to install *kde4* in Ubuntu:
```bash
sudo apt-get install python-kde4
```
For information, *KUbuntu 14.04.2 LTS* has been used to test this module.
The Linux standalone version has not been created and tested.
=> kde module implemented to steal credentials stored in KWallet

Windows/src/LaZagne/config/manageModules.py, Windows/src/LaZagne/softwares/git/gitforwindows.py
Hello,
I have created a small module and associated category in order to extract account's credentials for the "Git For Windows" application in case in which the user use the default disk storage mode on Windows.
I have tested it with the last version of the "Git For Windows" application.
I have based my implementatin on the SVN Tortoise module in order to stick to the development standards that you have defined.
Thanks in advance :)
=> Add account extractor for 'Git For Windows' application

Linux/lazagne/config/manageModules.py, Linux/lazagne/softwares/wallet/libsecret.py
I'm preparing to include lazagne for Linux to pupy. There is limited environment, so some more generic approaches should be used for wallets.
=> Add generic freedesktop protocol

Linux/lazagne/softwares/browsers/mozilla.py, Windows/lazagne/softwares/browsers/mozilla.py
When multiple profiles are in use and the first one get in an error path (no key3 file found, bad master password, and so on), no other profile is searched.
With this patch, the other profiles are searched, thus potentially getting saved passwords.
=> Fix mozilla when multiple profiles are in use

Windows/lazagne/softwares/sysadmin/cyberduck.py, Windows/lazagne/softwares/sysadmin/filezilla.py
In both cases the "directory" var is wrongly initialized due to the leading single backslash in the string appended when calling os.path.join(). It initializes to 'C:\FileZilla' and 'C:\Cyberduck' instead of the correct values.
This causes LaZagne to not find the necessary files and therefore stating that that cyberduck and filezilla are not installed.
edit: from the [python doc on os.path.join](https://docs.python.org/2/library/os.path.html#os.path.join): "_If a component is an absolute path, all previous components are thrown away and joining continues from the absolute path component._"
=> Issues with directory initialization for Cyberduck and FileZilla modules

Windows/lazagne/softwares/windows/creddump7/object.py
```
File "lazagne\softwares\windows\creddump7\newobj.py", line 210, in __init__
File "lazagne\softwares\windows\creddump7\object.py", line 70, in read_value
error: unpack requires a string argument of length 4
```
=> See traceback (creddump7->object.py)

Windows/lazagne/softwares/windows/creddump7/win32/domcachedump.py
```
File "lazagne\softwares\windows\creddump7\win32\domcachedump.py", line 73, in parse_decrypted_cache
File "encodings\utf_16_le.py", line 16, in decode
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 10-11: illegal UTF-16 surrogate
```
=> See traceback (domcachedump)

Windows/lazagne/softwares/windows/creddump7/win32/lsasecrets.py
```
File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 127, in get_secret_by_name
File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 78, in decrypt_secret
File "Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 8 in length
```
=> See traceback (lsasecrets)

Windows/lazagne/softwares/windows/creddump7/win32/lsasecrets.py
```
File "lazagne\softwares\windows\lsa_secrets.py", line 25, in run
File "lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 177, in get_file_secrets
File "lazagne\softwares\windows\creddump7\addrspace.py", line 79, in __init__
File "lazagne\softwares\windows\creddump7\addrspace.py", line 40, in __init__
IOError: [Errno 2] No such file or directory: 'c:\\docume~1\\admini~1\\locals~1\\temp\\asczhxaqk'
```
=> See traceback (bug in lsa secrets if no reg hives)

Windows/lazagne/config/change_privileges.py
Bad return value when called:
`token_sid, owner = get_token_info(hToken)`
=>  TypeError: 'bool' object is not iterable #278

Windows/lazagne/softwares/browsers/chromium_based.py
Sometime I got {'URL': '', 'Login': '', 'Password': ''} from Chrome module.
When at least one field is not empty this information can ca applied but otherwise it's a rubbish, so we can skip it.
=> Filter fully empty credentials

Windows/lazagne/config/run.py, Windows/lazagne/config/users.py
Hello. Due to:
```
File "\lazagne\config\run.py", line 190, in run_lazagne
File "\getpass.py", line 157, in getuser
ImportError: No module named pwd
```
This exception happens in XP/2003.
=> Windows getting user name method change

Windows/lazagne/config/winstructure.py
I think it's bad to return False if failed because it's not a boolean function, it should return None (empty return) if fails. Also casting False to str will cause smth like this:
>  'URL': 'http://192.168.0.1', 'Login': 'admin', 'Password': False
=> Change Win32CryptUnprotectData return value

Windows/lazagne/softwares/sysadmin/opensshforwindows.py
Since 2014 there is a new standard used by ssh-keygen which creates openssh keys with "OPENSSH PRIVATE KEY" header. This standard, however, does not make it easy to understand if the key has a passphrase or not (as compared to the old RSA standard which specifies "ENCRYPTED" label for an RSA key having a passphrase). Anyway, my fix could still allow to recover some new standard keys which have no passphrase. I stumbled upon this while creating a new key pair and placing it (private key) into the .ssh folder for my Windows git client.
=> Enhancement for SSH key harvesting

Linux/lazagne/softwares/wifi/wifi.py
Corrects output of SSID to reflect the actual SSID, not the config filename.
=> SSID output correction

Linux/lazagne/softwares/browsers/mozilla.py, Linux/lazagne/softwares/wallet/libsecret.py
Some of the username/password outputs on python3 were showing up as:
```
Login: b'username@website.com'
Password: b'mySuperStrongPa$$word'
```
I've appended `.decode('utf8')` to those lines, which fixes the issue, and works on both python2 & 3.
It's possible that there are more modules which have this issue, but of those that I have on my system, these are the only ones that had this issue.
=> Python3 fixes

Linux/lazagne/softwares/browsers/chrome.py
On python2, attempting to read from the database would result in the error `database disk image is malformed`.
This fix works on both python2 & python3.
=> fix python2 error

Linux/lazagne/config/write_output.py, Mac/lazagne/config/write_output.py, Windows/lazagne/config/write_output.py, Windows/lazagne/softwares/sysadmin/opensshforwindows.py
Hi,
this PR addresses two issues that I detected when running LaZagne:
- First, the JSON dump outputs an invalid JSON when special characters are in the result (for example, newline characters or quotes). In this case, if you try to load the content of the output file with `json.loads` (for instance) you will get an exception. This is what is described in issue #226 regarding multi-line strings for SSH keys in the JSON output. This is due to the `decode('unicode-escape')` [instruction](https://github.com/AlessandroZ/LaZagne/blob/c96744a2574a6f00dbbb73a009f8d042181d1a8d/Windows/lazagne/config/write_output.py#L350) when the JSON file is written:
```
f.write(pretty_json.decode('unicode-escape').encode('UTF-8'))
```  
This will decode the special characters (\n for newline or \" for quotes) …
=> Dump valid JSON file and minor correction for opensshforwindows keys

.travis.yml
Do not hard-code __Trusty__ because it reaches its end-of-life next month.
https://wiki.ubuntu.com/Releases
Also, [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
=> Travis CI: Do not hard-code Trusty, it EOLs next month

Linux/lazagne/config/homes.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/AlessandroZ/LaZagne
$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./Linux/lazagne/config/homes.py:117:24: F632 use ==/!= to compare str, bytes, and int literals
if 'DBUS_SESSION_BUS_ADDRESS' is os.environ:
^
1     F632 use ==/!= to compare str, bytes, and int literals
1
```
=> Typo: str is os.environ --> str in os.environ

Mac/lazagne/softwares/browsers/mozilla.py
https://github.com/AlessandroZ/LaZagne/blob/master/Mac/lazagne/config/module_info.py#L32
```
./Mac/lazagne/softwares/browsers/mozilla.py:117:13: F821 undefined name 'self'
self.error(u'An error occurred while reading profiles.ini: {}'.format(e))
^
```
=> Need 'self' to get to ModuleInfo.error() on line 116

Mac/lazagne/softwares/browsers/mozilla.py, Windows/lazagne/config/DPAPI/crypto.py, Windows/lazagne/config/crypto/pyaes/aes.py, Windows/lazagne/config/crypto/pyaes/util.py, Windows/lazagne/softwares/browsers/mozilla.py, Windows/lazagne/softwares/memory/libkeepass/pureSalsa20.py
These relatively minor changes follow the Python porting best practice [___use feature detection instead of version detection___](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).  They make it easier to lint the code to spot Python 3 incompatibilities and in the case of __pureSalsa20.py__ define __long__ for compatibility with both Python 2 and Python 3.
=> General exceptions --> specific exceptions

.travis.yml
The Python 3 run is in __allow_failures__ mode until the port to Python 3 is complete.
=> Travis CI: Add linting runs in Python 2 and Python 3

.travis.yml, requirements.txt
Create a requirements.txt that uses https://www.python.org/dev/peps/pep-0508 in conditionally install on Linux, Mac, Windows.  Upgrade the wine Python from 2.7.9 to 2.7.16 to ensure we have a pip that understands PEP508.
=> Create a single requirements.txt for all platforms

.travis.yml, Linux/requirement.txt, Windows/requirement.txt
Is is OK to drop __pywin32-224-cp27-none-win_amd64.whl__ or not?
If not, is it OK to pip install it?  https://pypi.org/project/pywin32
=> Finish the migration to the new requirements.txt

Linux/lazagne/config/write_output.py, Mac/lazagne/config/write_output.py, Windows/lazagne/config/write_output.py
As discussed at: https://github.com/AlessandroZ/LaZagne/issues/295#issuecomment-426696254
Also, simplify with __dict.get()__ and misc flake8 cleanup.
* [__Python 2.7.15 on Darwin x86_64: i386__](https://travis-ci.com/cclauss/LaZagne/jobs/189388027#L179)
* [__Python 2.7.16 on Windows AMD64: AMD64 Family 6 Model 45 Stepping 7, GenuineIntel__](https://travis-ci.com/AlessandroZ/LaZagne/jobs/189388942#L2494)
=> Add platform info to BANG BANG banner

Windows/lazagne/softwares/browsers/chromium_based.py
https://www.howtogeek.com/255653/how-to-find-your-chrome-profile-folder-on-windows-mac-and-linux/
Any newly created profiles directory would be named "Profile X", which was missed by this script.
=> Automatic join all other additional profiles.

.travis.yml, Linux/lazagne/config/crypto/pyDes.py, Linux/lazagne/config/crypto/pyaes/aes.py, Linux/lazagne/config/crypto/pyaes/util.py, Mac/lazagne/config/crypto/pyDes.py, Windows/lazagne/config/crypto/pyDes.py
Remove Python 3 __allow_failures__ mode from Travis CI
=> Travis CI: Let's pass the lint tests on Python 3 again

Linux/lazagne/config/write_output.py, Linux/lazagne/softwares/wifi/wifi.py
fixes #420
The same change could be made for other outputs as well, but none (that I see) are as jarring as the WiFi output.
This change is compatible with both Python2 & Python3.
=> fix wifi output order

Windows/lazagne/config/users.py
Hi!
>   File "~\lazagne\config\run.py", line 189, in run_lazagne
> AttributeError: 'NoneType' object has no attribute 'endswith'
=> If fail to get username via winapi

Linux/lazagne/softwares/browsers/chrome.py
If the username is empty that means that there's no saved passwords for this site
fixes #419
=> [Linux - Chrome] check for empty username

Windows/lazagne/softwares/git/gitforwindows.py
There was an error in import statement for python3 in gitforwindows.py. So, error have been occurred on collecting credentials for git in python3/windows.
=> improve import statement

Linux/lazagne/softwares/git/gitforlinux.py, Windows/lazagne/softwares/git/gitforwindows.py
Credentials are stored as urlencoded string. If host_name, username or password contains specialchars then it collects undecoded.
=> Unquote credentials in git

Windows/lazagne/config/write_output.py
Fixed bug with output: printed that password is not found in case if `password key` is not capitalised. For example: "IMAP Password".
=> Improve write output

Windows/lazagne/config/winstructure.py, Windows/lazagne/softwares/windows/vault.py
For Windows 7 collects logins only from Vault, not passwords. Behaviour for later versions of windows has not been changed (logins and passwords successfully collected).
Password's collecting for Win 7 fails for some reason on function _VaultGetItem_ ([https://github.com/MyLoginOnGitHub/LaZagne/blob/7727bc3bab2d228e5257804088f7f56202d2828d/Windows/lazagne/softwares/windows/vault.py#L48](url)) with status code 87 (ERROR_INVALID_PARAMETER, https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-).
I've done as in following, but it fails.
https://github.com/EmpireProject/Empire/blob/master/data/module_source/credentials/Get-VaultCredential.ps1
https://github.com/byt3bl33d3r/SILENTTRINITY/blob/master/silenttrinity/core/teamserver/modules/boo/src/dumpVaultCredentials.boo …
=> Added limited vault support support for Windows 7

Linux/lazagne/config/constant.py, Mac/lazagne/config/constant.py
The Linux and Mac version constant hadn't been updated in a while, resulting in an older version number being printed when executing `./laZagne.py --version`.
=> update version in contant.py

Linux/lazagne/softwares/wallet/libsecret.py
When Chrome is the only Chromium browser installed on a system, there will not be a secret called "Chromium Safe Storage". Instead, it is called "Chrome Safe Storage".
Fixes https://github.com/AlessandroZ/LaZagne/issues/489
=> fix chrome password retrieval on linux

Linux/lazagne/config/constant.py, Linux/lazagne/softwares/browsers/chrome.py, Linux/lazagne/softwares/wallet/libsecret.py, README.md
Currently tested with Brave, but it should work with others as well.
This also completes support for Chromium now, which was only partially working before.
To add others, just add their config directory to `constant.chrome_dirs`
=> Reworked Chrome code to support Chromium-based browsers

Linux/lazagne/config/constant.py, Linux/lazagne/config/manage_modules.py, Linux/lazagne/softwares/browsers/chrome.py
Since we're now collecting passwords from multiple chromium-based browsers, it makes sense to give each one it's own section, similar to Firefox.
=> Divide Chromium-based browser passwords according to browser

Linux/lazagne/softwares/browsers/chrome.py, Linux/lazagne/softwares/browsers/mozilla.py, README.md
Chromium-based:
- SlimJet
- Dissenter-Browser
Firefox-based:
- IceCat
- WaterFox
I removed Cyberfox because it is an outdated browser which hasn't been updated in several years.
The remaining Firefox-based browser commented out to test are unavailable for Linux.
I also tested several browser which didn't work. I left them commented out with FIXME notations in case someone wants to look at them:
- **SuperBird**: This one had a lot of tracebacks, presumably it uses a different method for storing the passwords than standard Chromium-based browsers.
- **Vivaldi & Whale**: These are a little weird. They each (if included individually, or the last of both if you uncomment both of them) fail at this line. 
https://github.com/AlessandroZ/LaZagne/blob/f5425058102f18a643a5734eeef6a897af182e67/Linux/ …
=> Add support for more browsers on Linux

Linux/lazagne/config/manage_modules.py, Linux/lazagne/softwares/browsers/chromium_based.py, README.md, requirements.txt
and add Vivaldi to supported browsers
When Chrome v80 support was added to Windows (#475, https://github.com/AlessandroZ/LaZagne/commit/db3461a26ea7c246f5cee00a7630c4bf7e610861), it wasn't added to Linux. This commit adds it (and its dependency, `pycryptodome`), to Linux. It should also be ported to Mac, but I don't have one to test.
I also renamed the class to `ChromiumBased` to match the Windows version, since it now extracts passwords from many Chromium based browsers, and not just Chrome.
The final change was adding Vivaldi (which didn't work before, #516), since with this update it works for me.
=> Support Chrome v80+ on Linux

Windows/lazagne/config/manage_modules.py, Windows/lazagne/softwares/memory/onepassword.py
I have added support for 1Password7 for Windows.
The module attempts to extract the password managers login details such as the username, url, secret key, and master password by utilizing the MemWorker class and regular expressions.
This capability has been extracted from my script:
https://github.com/notdeclan/1password-memory-dump-analyzer
=> Added 1Password7 (Windows) module

Mac/laZagne.py
This solution to https://github.com/AlessandroZ/LaZagne/issues/431#issuecomment-552210931 should work in both Python 2 and Python 3.
% `python3`
```
>>> dic = {"A": 0}
>>> dic_tmp = {"B": 1}
>>> dict(dic.items() + dic_tmp.items())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
>>> dict(list(dic.items()) + list(dic_tmp.items()))
{'A': 0, 'B': 1}
```
---
% `python2`
```
>>> dic = {"A": 0}
>>> dic_tmp = {"B": 1}
>>> dict(dic.items() + dic_tmp.items())
{'A': 0, 'B': 1}
>>> dict(list(dic.items()) + list(dic_tmp.items()))
{'A': 0, 'B': 1}
```
=> Mac LaZagne: Adding two dicts together in Python 3

Mac/lazagne/softwares/system/chainbreaker_module/pbkdf2.py
Fixes #431
https://docs.python.org/2/library/sha.html is deprecated as sha1() has moved to https://docs.python.org/3/library/hashlib.html
This change should work in both Python 2 and Python 3.
=> Mac LaZagne fix for #431 from hashlib import sha1

Windows/lazagne/softwares/chats/pidgin.py
The condition is never met, even if name and password exist.
Checking if elements are not equal to `None` makes it work.
=> Fix condition never met

Linux/hook-sys.py, Linux/lazagne/config/constant.py, Linux/lazagne/config/manage_modules.py, Linux/lazagne/config/soft_import_module.py, Linux/lazagne/softwares/browsers/chromium_based.py, Linux/lazagne/softwares/browsers/chromium_browsers.py, Linux/lazagne/softwares/browsers/firefox_browsers.py, Linux/lazagne/softwares/browsers/mozilla.py, Linux/lazagne/softwares/memory/mimipy.py
As mentioned in #558, I think it is good idea to try to run LaZagne with modules available on current system.  
This PR does not resolve this issue, but just demonstrates proof of concept that it could be done **without editing modules itself**. For completely resolve it same thing should be done for Windows and MacOS. This PR is only affects Linux.  
I used **dynamically import for all modules**. Failed to import modules are appeared in category `unused`. If they a called (with option `all`) they call method `error` and pass meassage with exception as parameter.  
I also provide hook for **PyInstaller**. It need to set parameter `--additional-hooks-dir` for PyInstaller. Example:  
`pyinstaller --additional-hooks-dir=. --onefile ./laZagne.py`
I have tested this code. If @AlessandroZ think …
=> Do not use modules with broken depensences for linux

Linux/lazagne/softwares/browsers/chromium_browsers.py, README.md
Microsoft Edge has been released to the stable channel for Linux.
=> [Linux] Add Microsoft Edge (stable)

Windows/lazagne/config/DPAPI/masterkey.py
Previously code has just silently failed because of lines 292-293. It expected `self.raw` to be a binary data in `Eater.read()` method, but python3 decoded it to a string by default.
=> Fixed bug in adding CREDHIST file.

Windows/lazagne/config/DPAPI/credhist.py, Windows/lazagne/config/DPAPI/masterkey.py
=> Fix multiple issue

Mac/laZagne.spec, Mac/lazagne/config/manage_modules.py, Mac/lazagne/config/soft_import_module.py, Mac/lazagne/softwares/browsers/firefox_browsers.py, Mac/lazagne/softwares/browsers/mozilla.py
Do not use modules with broken depensences for Mac OS and create `lazagne.spec` file to compile new code in pyinstaller.  
**WARNING!!** I have no Mac, so **I haven't tested it**, but it all same as #564.  
I have only done PR as in [comment](https://github.com/AlessandroZ/LaZagne/pull/564#issuecomment-859462184).
=> Do not use modules with broken depensences

Linux/lazagne/softwares/sysadmin/env_variable.py, Linux/lazagne/softwares/sysadmin/fstab.py, Linux/lazagne/softwares/sysadmin/shadow.py, Linux/lazagne/softwares/wallet/libsecret.py
I did some small improvements in the Linux modules `fstab`, `libsecret`, `env_variable` and `shadow`. The individual commit messages describe what I changed and why.
Please let me know if this is fine or whether I should change something.
(Besides, I have a question not related to the PR: I noticed that (at least) the wallet modules require the `dbus-python` package but it is not listed in `requirements.txt`. Is this on purpose? Maybe because building it depends on `cmake` and `dbus-python-devel` system packages? Though in general I would have expected that this is included in `requirements.txt`. Should I add it?)
=> Improved multiple Linux modules

Linux/lazagne/softwares/browsers/chromium_based.py
From some tests performed I determined that the credential retrieval does not work with passwords over ~106 bytes long.
Changing the Mode of operation from GCM to CBC fixes this.
Not sure if between version 80 and 129 the encryption mode changed, or if passwords larger than 106 bytes were never tested.
=> Fix issue with large passwords

Windows/lazagne/softwares/sysadmin/openvpn.py
In current version of master it fails with the exception `'str' object has no attribute 'decode'`. I have fix it and I also improved it with more collected data:
- Username
- Entire config file
- Private key (pkcs12 directive)
- Private key password (if used)
=> Improve openvpn for windows

Mac/lazagne/softwares/browsers/mozilla.py
This should fix #658. I have no MAC, so I not able to check it. But I absolutely sure It shoulf fix it. May be it will fail again with some another error =)
=> Fix error "'Mozilla' object has no attribute 'getLoginData'"
