- Windows/src/LaZagne/laZagne.py
I made all the comments follow the same format. One space away form the #, and the first letter capitalized.
> Fixed the comment format

- Linux/src/config/manageModules.py
- Linux/src/softwares/wifi/wpa_supplicant.py
wpa_supplicant is another wifi manager for linux.
This add a module to look for ssid/password in wpa_supplicant configuration file
> add new module for wpa_supplicant in Linux

- Windows/src/LaZagne/softwares/browsers/opera.py
print_debug was called with 1 argument -> now is called with 2
> Fix Opera Bug

- Windows/src/LaZagne/config/manageModules.py
- Windows/src/LaZagne/softwares/games/galconfusion.py
- Windows/src/LaZagne/softwares/games/kalypsomedia.py
- Windows/src/LaZagne/softwares/games/roguestale.py
- Windows/src/LaZagne/softwares/games/turba.py
Started adding some of the passwords from games to LaZagne. Here's the first one: just a simple hash extraction from the game Rogue's Tale.
> Added games category and module for Rogue's Tale

- Windows/src/LaZagne/config/manageModules.py
- Windows/src/LaZagne/softwares/maven/mavenrepositories.py
- Windows/src/LaZagne/softwares/sysadmin/apachedirectorystudio.py
- Windows/src/LaZagne/softwares/sysadmin/opensshforwindows.py
Hello,
I have added 3 extractors in order to extract:
1) The repositories's credentials used by Maven java build tool:
3 cases are handled:
* Authentication using password protected with the master password (encrypted)
* Authentication using password not protected with the master password (plain text)
* Authentication using private key
2) The connections credentials for "Apache Directory Studio" (ldap browser) application.
3) The unprotected private keys for "OpenSSH" application.
Thanks in advance  :+1:
> Add new extractors

- Windows/lazagne/softwares/browsers/ie.py
avoid seeing a powershell console popping up and closing when running hidden like in pupy
> fix powershell console poping up

- Windows/lazagne/softwares/browsers/mozilla.py
added credits for decryption functions and BSD database parsing
> added credit for decryption functions

- Windows/lazagne/config/manageModules.py
- Windows/lazagne/softwares/php/composer.py
Hi,
This is an extractor for PHP Composer credentials when they are defined at global level.
I have refreshed my fork before to commit+push files.
Thanks in advance.
> Extractor for  PHP Composer creds

- Windows/lazagne/softwares/mails/outlook.py
Should fix Outlook scan and now display SMTP password.
> Fix Outlook scan

- Windows/laZagne.py
See: https://github.com/AlessandroZ/LaZagne/issues/101
Tested.
> Fix selected module with args

- Mac/laZagne.py
I suppose there is issue here to, not tested on MAC.
> Fix args issue on MAC

- Linux/laZagne.py
Same issue with args for Linux.
Tested.
> Fix args for Linux

- Linux/laZagne.py
- Linux/lazagne/config/homes.py
- Linux/lazagne/config/manageModules.py
- Linux/lazagne/config/write_output.py
- Linux/lazagne/softwares/browsers/chrome.py
- Linux/lazagne/softwares/browsers/mozilla.py
- Linux/lazagne/softwares/browsers/opera.py
- Linux/lazagne/softwares/chats/jitsi.py
- Linux/lazagne/softwares/chats/pidgin.py
- Linux/lazagne/softwares/databases/dbvis.py
- Linux/lazagne/softwares/databases/sqldeveloper.py
- Linux/lazagne/softwares/databases/squirrel.py
- Linux/lazagne/softwares/mails/clawsmail.py
- Linux/lazagne/softwares/sysadmin/aws.py
- Linux/lazagne/softwares/sysadmin/cli.py
- Linux/lazagne/softwares/sysadmin/docker.py
- Linux/lazagne/softwares/sysadmin/env_variable.py
- Linux/lazagne/softwares/sysadmin/filezilla.py
- Linux/lazagne/softwares/sysadmin/ssh.py
- Linux/lazagne/softwares/wallet/libsecret.py
https://github.com/AlessandroZ/LaZagne/issues/121
I don't have all those software to check that something wasn't broken, but looks like most works ok. To feel the difference try to run as root on PC with running user sessions
> Try to extract passwords from all user contexts (Linux)

- Windows/lazagne/softwares/windows/creddump7/addrspace.py
Fixes one of the issues in #135
> def close() --> def close(self)

- Windows/lazagne/softwares/memory/libkeepass/pureSalsa20.py
Fixes one of the issues in #135
> raise exception() --> raise Exception()

- Linux/requirement.txt
- Mac/requirement.txt
- README.md
- Windows/requirement.txt
These files allows to install some of dependencies. For example "python-dbus" should be installed with apt-get for some debian based OS (Ubuntu in my case), so I changed wiki accordingly.
> Issue #187

- Windows/lazagne/config/manageModules.py
- Windows/lazagne/softwares/chats/psi.py
- Windows/lazagne/softwares/databases/postgresql.py
- PostgreSQL
Based on:
https://www.postgresql.org/docs/9.1/static/libpq-pgpass.html
Example file content:
```
localhost:5432:*:postgres:root
127.0.0.1:5432:*:postgres:root
```
- PSI/PSI+
Decryption code based on https://github.com/jose1711/psi-im-decrypt
> postgresql and PSI/PSI+ credentials grabbers

- Windows/lazagne/softwares/browsers/mozilla.py
The situation when key3.db version updates to key4.db version and both files are present.
> mozilla update fix

- Windows/lazagne/config/change_privileges.py
File "\lazagne\config\changePrivileges.py", line 64, in ListSids
File "\psutil\__init__.py", line 551, in as_dict
File "\psutil\__init__.py", line 719, in username
File "\psutil\_pswindows.py", line 578, in wrapper
File "\psutil\_pswindows.py", line 743, in username
WindowsError: [Error 1722] The RPC server is unavailable
> Once time I had such error.

- Windows/laZagne.py
- Windows/lazagne/config/DPAPI/masterkey.py
- Windows/lazagne/config/change_privileges.py
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/config/write_output.py
- Windows/lazagne/softwares/browsers/chromium_based.py
- Windows/lazagne/softwares/browsers/mozilla.py
- Windows/lazagne/softwares/browsers/ucbrowser.py
- Windows/lazagne/softwares/mails/thunderbird.py
Add new browsers: UC Browser, CyberFox, IceDragon, K-Meleon, IceCat
Fix program fail when Windows username contains non-ascii characters (#169 issue was closed as solved but the program was failing with this same error on my system)
Fix DPAPI unicode error when firefox password contains non-ascii character (#242 but needs more testing)
Fixed first from [this issue](https://github.com/AlessandroZ/LaZagne/issues/231#issuecomment-400243213) as I faced this error too. Still don't know about the second one.
This project has a lot of encoding-related errors, this is one of the reasons I hate python2
> Improve Mozilla class to support firefox-based browsers, error fixes

- Windows/laZagne.py
- Windows/lazagne/config/write_output.py
- Windows/lazagne/softwares/browsers/chromium_based.py
- Windows/lazagne/softwares/browsers/ucbrowser.py
Fix encoding error when computer name (hostname) contains non-ascii chars
Also want to know your opinion about making the project pep8-compliant? I see you like tabs but this is not very pythonic.
- Replace tabs with 4 spaces
- Use `CamelCase` for classes only
- Use `ALL_UPPER_CASE` for global constants
- Use `snake_case` for everything else
> Fix UC Browser user impersonation, encoding error again 😅

- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/config/winstructure.py
- Windows/lazagne/softwares/browsers/chromium_based.py
- Windows/lazagne/softwares/browsers/ie.py
- Windows/lazagne/softwares/browsers/mozilla.py
- Windows/lazagne/softwares/browsers/ucbrowser.py
- Windows/lazagne/softwares/windows/creddump7/win32/hashdump.py
Fix encoding when chromium password contains non-ascii characters
Fix MD5 global variable not found error
Refactor code
Should fix #242
> Fix encoding errors, MD5 variable error, code refactor

- Windows/lazagne/softwares/chats/pidgin.py
- Windows/lazagne/softwares/chats/psi.py
- Windows/lazagne/softwares/chats/skype.py
- Windows/lazagne/softwares/databases/dbvis.py
- Windows/lazagne/softwares/databases/postgresql.py
- Windows/lazagne/softwares/databases/robomongo.py
- Windows/lazagne/softwares/databases/sqldeveloper.py
- Windows/lazagne/softwares/databases/squirrel.py
- Windows/lazagne/softwares/games/galconfusion.py
- Windows/lazagne/softwares/games/kalypsomedia.py
- Windows/lazagne/softwares/games/roguestale.py
- Windows/lazagne/softwares/games/turba.py
- Windows/lazagne/softwares/git/gitforwindows.py
- Windows/lazagne/softwares/mails/outlook.py
- Windows/lazagne/softwares/mails/thunderbird.py
- Windows/lazagne/softwares/maven/mavenrepositories.py
- Windows/lazagne/softwares/memory/libkeepass/common.py
- Windows/lazagne/softwares/memory/libkeepass/crypto.py
- Windows/lazagne/softwares/memory/libkeepass/hbio.py
- Windows/lazagne/softwares/memory/libkeepass/kdb4.py
- Windows/lazagne/softwares/memory/libkeepass/pureSalsa20.py
Also I've found these bugs while refactoring the code:
```
Windows/lazagne/softwares/databases/robomongo.py:84 path not found
Windows/lazagne/softwares/memory/libkeepass/kdb4.py:84 self._write_header not defined
Windows/lazagne/softwares/memory/libkeepass/kdb4.py:268 self.header is not defined
Windows/lazagne/softwares/memory/libkeepass/kdb4.py:271 self.in_buffer is not defined
Windows/lazagne/softwares/memory/libkeepass/kdb4.py:274 self.in_buffer is not defined
Windows/lazagne/softwares/chats/skype.py:99 constant.path is not defined
```
I didn't have much time to figure out the flow of each module to fix these bugs so maybe take a look if you have free time.
> PEP8 some code

- Windows/lazagne/config/DPAPI/masterkey.py
```
File "lazagne\config\dpapi_structure.py", line 36, in are_masterkeys_retrieved
File "lazagne\config\dpapi_structure.py", line 94, in check_credentials
File "lazagne\config\DPAPI\masterkey.py", line 359, in try_credential
AttributeError: 'NoneType' object has no attribute 'decrypt_with_password'
```
> Error if no master key

- Windows/lazagne/softwares/browsers/mozilla.py
Processing "IsRelative" parameter in "profiles.ini" added
http://kb.mozillazine.org/Profiles.ini_file
> Relative profiles in Mozilla

- Windows/lazagne/config/change_privileges.py
- Windows/lazagne/config/winstructure.py
I'm not sure it fixes the main problem, but with this crash goes away..
> Hopefully fix https://github.com/AlessandroZ/LaZagne/issues/287

- Windows/lazagne/softwares/chats/skype.py
> Small improvement in dictionary_attack

- Windows/lazagne/softwares/browsers/mozilla.py
Otherwise exception "IOError: [Errno 2] No such file or directory" may happens.
> Check logins.json exists, better file opening

- README.md
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/wsl.py
Extract hashes from /etc/shadow in Windows Subsystem for Linux (WSL).
If old WSL look into %LOCALAPPDATA%/lxss/rootfs/.
If new WSL look into %LOCALAPPDATA%/Packages for all distributions.
Info here: http://archive.hack.lu/2018/A_Cervoise-Backdoor_Bash_on_Windows.pdf
> Adding WSL module.

- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/multimedia/eyecon.py
Just a basic module to extract passwords from application eyeCON
eyeCON software WAll management software
infos at http://www.eyevis.de/en/products/wall-management-software.html
> EyeCON Password extraction module

- Windows/lazagne/softwares/sysadmin/vnc.py
> One more WinVNC reg key

- Windows/lazagne/config/users.py
> Decode string

- README.md
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/openvpn.py
Support for Open VPN GUI for Windows
> OpenVPN support

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/chats/psi.py
- README.md
Based on the Windows version
I'm not sure why 'Jitsy' was listed in the ReadMe - there's no mention of it in the code.
> Add Psi chat support for Linux

- Windows/lazagne/softwares/games/kalypsomedia.py
We are importing the wrong class to match with line 32.
> Undefined name: RawConfigParser --> ConfigParser

- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/iiscentralcertp.py
This is a module to get passwords stored when Central Cert Provider is used in IIS Server.
It could store a Shared Resource, a Username, a Password and a Private Key Password (for Certs)
In the next URL you can get an idea of what Central Cert Provider is, and how to enabled it.
https://blogs.msdn.microsoft.com/kaushal/2012/10/11/central-certificate-store-ccs-with-iis-8-windows-server-2012/
Thanks!!
> Central Cert Provider - IIS Server

- .travis.yml
$ __pyinstaller --onefile Mac/laZagne.py__
$ __ls -l dist__
`-rwxr-xr-x  1 travis  staff  4816393 Mar 30 05:28 laZagne`
$ __dist/laZagne all__
```
|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
[-] Chrome safe storage key has not been retrieved, cannot decrypt passwords
------------------- Hashdump passwords -----------------
[+] 0 passwords have …
```
>  Travis CI: Add a parallel build on macOS

- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/iisapppool.py
Just a little script to retrieve passwords configured into IIS Application Tool
More information:
https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities
https://amoghnatu.net/2015/01/15/get-password-for-iis-application-pool-account/
> IIS Application Pool - Password Retrieval

- Windows/lazagne/config/DPAPI/blob.py
- Windows/lazagne/config/DPAPI/crypto.py
- Windows/lazagne/config/winstructure.py
- Windows/lazagne/softwares/browsers/mozilla.py
- Windows/lazagne/softwares/wifi/wifi.py
3DES was broken. Also DPAPI requires some refactoring (which is up to you).
There should be some cache of gid/sid/password tuples, to reduce time to decrypt keys again and again..
> Various fixes

- README.md
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/filezillaserver.py
Add a module for FileZIlla Server (Windows only software). The server stored the last connection in a XML file with this format:
```xml
<FileZillaServer>
<Settings>
<Item name="Last Server Address" type="string">localhost</Item>
<Item name="Last Server Port" type="numeric">14147</Item>
<Item name="Last Server Password" type="string">123456</Item>
<Item name="Always use last server" type="numeric">0</Item>
<Item name="Start Minimized" type="numeric">0</Item>
<Item name="User Sorting" type="numeric">0</Item>
</Settings>
</FileZillaServer>
```
> Add FileZilla Server (Windows)

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/sysadmin/apachedirectorystudio.py
Module for Apache Directory Studio for Linux (code from Windows module).
> Add module for ApacheDirectoryStudio for Linux

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/sysadmin/gftp.py
- README.md
Add gFTP module for Linux.
Add gFTP and ApacheDirectoryStudio in README.md.
> Add gFTP (Linux)

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/sysadmin/keepassconfig.py
- README.md
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/filezilla.py
- Windows/lazagne/softwares/sysadmin/keepassconfig.py
Crawl KeePass 1, KeePass 2 and KeePassX configuration file (Windows, Linux) to find kdb/kdbx and keyfiles.
> Add KeePass config file crawlers

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/sysadmin/grub.py
- README.md
Sources: https://www.justegeek.fr/proteger-ledition-du-grub-avec-mot-de-passe/ https://www.tecmint.com/password-protect-grub-in-linux/
> Add Grub passwords and hashes

- Linux/lazagne/config/manage_modules.py
- Linux/lazagne/softwares/git/gitforlinux.py
> Create git for linux

- Linux/lazagne/softwares/memory/mimipy.py
Fixed output difference in python2 and python3 for Linux/mimipy
> Fix issue #421

- Linux/lazagne/softwares/git/gitforlinux.py
Fixed 2 lapses in git for linux
> Fix bugs in gitforlinux

- Windows/lazagne/softwares/mails/outlook.py
Added support of different versions of outlook. And bug fixed.
> Upgrade outlook

- Windows/lazagne/softwares/browsers/mozilla.py
> Fix bug in firefox

- Linux/lazagne/softwares/browsers/chrome.py
same issue as https://github.com/AlessandroZ/LaZagne/issues/421
> Fixed python3 output

- Windows/lazagne/config/winstructure.py
- Windows/lazagne/softwares/browsers/chromium_based.py
- Windows/lazagne/softwares/browsers/ie.py
- Windows/lazagne/softwares/chats/skype.py
- Windows/lazagne/softwares/mails/outlook.py
- Windows/lazagne/softwares/svn/tortoise.py
- Windows/lazagne/softwares/sysadmin/cyberduck.py
- Windows/lazagne/softwares/sysadmin/openvpn.py
- Windows/lazagne/softwares/sysadmin/rdpmanager.py
Closes #456. 
Refactor Win32CryptUnprotectData 
Also update decoding for outlook passwords
> Refactor 456

- Windows/lazagne/softwares/browsers/ie.py
Tested on Windows7 IE10 using Python3. It should to test it on another versions of Windows and IE. Also need to test it on Python2. I think, it should to work, but it's better to test.
In previous version there was many wrong logins and passwords from service data. This parse algorithm should to allow to filter only real credentials.
Also previous version did not supported Python3.
> Update parse bytes algorithm for ie

- Windows/lazagne/softwares/windows/credman.py
Added UTF-16 decoding for password
> Update password decoding for credman

- README.md
the extra entry was added in 3e629a0.
> removed duplicate row "WiFi"

- Linux/lazagne/softwares/wallet/libsecret.py
I forgot, I haven't done Python in a while...
> python uses or, not ||

- Linux/lazagne/config/write_output.py
>  Fix file output for Python3

- Windows/lazagne/softwares/browsers/chromium_based.py
Added chromiumEdge support for windows. 
This solves #498
> Added chromiumEdge support for windows

- .travis.yml
https://github.com/pyinstaller/pyinstaller/releases
Python on Wine https://appdb.winehq.org/objectManager.php?sClass=application&iId=7578
> Travis CI: pyinstaller v4.0 drops support for legacy Python

- README.md
#530 Added Edge
But the README didn't get updated, so I fixed it.
> 📝Update Supported Browsers

- Linux/lazagne/config/module_info.py
- Linux/lazagne/config/soft_import_module.py
Added python2 support for recent changes in #560
> Added python2 support

- Linux/hook-sys.py
- Linux/laZagne.spec
Use .spec file to handle hidden imports for pyinstaller
> Use pyinstaller's .spec file instead of hook file

- Windows/lazagne.spec
- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/config/soft_import_module.py
- Windows/lazagne/softwares/browsers/chromium_based.py
- Windows/lazagne/softwares/browsers/chromium_browsers.py
- Windows/lazagne/softwares/browsers/firefox_browsers.py
- Windows/lazagne/softwares/browsers/mozilla.py
Use dynamic import for Windows like in #560.  
I have tested the code, all works correctly. But I have no pyinstaller on windows. **Please**, test if pyinstaller works fine before merge.  
If you have no pyinstaller fow Windows too, tell me and I will install it to check.  
By the way, I have no MAC at all. I could to do the same thing for MAC, but I could not test it anywhere
> Do not use modules with broken depensences

- Linux/lazagne/softwares/browsers/chromium_browsers.py
Currently only Dev & Beta editions are available.
> add Microsoft Edge for Linux

- README.md
I forgot to update it when adding support for them...
> update supported browser list

- Windows/lazagne/config/manage_modules.py
- Windows/lazagne/softwares/sysadmin/mRemoteNG.py
New module: mRemoteNG passwords recovery for Windows.
> mRemoteNG for Windows

- Windows/lazagne/softwares/sysadmin/rdpmanager.py
issue:  https://github.com/AlessandroZ/LaZagne/issues/614
> fix: add parse_xml in rdpmanager
